-- teste pratico corpsystem

create database PDV;

use pdv;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE VENDAS (
    ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    DATA_VENDA TIMESTAMP NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE ITENS_VENDA (
    ID_ITEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);



